#include <SDL2/SDL_gamecontroller.h>
#include <SDL2/SDL_mixer.h>
#include "ctype.h"
#include <time.h>
#include "defs.h"
#include "math.h"
#include "SDL2/SDL.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "structs.h"
#include "stdbool.h"